apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-svc
    env: dev
    tier: two
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      targetPort: 6379
      port: 6379
  # which pods do I expose as a service, other end of labels.
  selector:
    name: redis
    env: dev
    tier: two