apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: two
    env: dev
    name: redis
spec:
  imagePullSecrets:
  # not required for redis(public repo)
    - name: regcred
  containers:
    - name: redis
      image: redis:latest
      resources:
        requests:
          cpu: "250m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
      ports:
        - containerPort: 6379

